language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

matrix:
    allow_failures:
        - php: 7
        - php: hhvm
    fast_finish: true

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction

script:
    - vendor/bin/phpunit --coverage-text
    - vendor/bin/phpcs --standard=PSR1 ./src
    - vendor/bin/php-cs-fixer fix .

notifications:
    email:
        - raphael@de-freitas.net
